### ISSUE TITLE
site_base.html requirement missing

### ISSUE THREAD

**Issue by nachopro** [rizumu/django-podcasting#18]
I'm trying to use django-podcasting but a site_base.html is required when I open /podcasts/ url.
What content site_base.html must contain (eg: {{ block podcasts }}, etc, etc) in order to that urls displays the content?
Thanks!

**Comment by rizumu** [comment]
I wonder if that shouldn't be required, but it is a pattern I and others have been following for years so it shouldn't be too much to work around. I imagine in the worst case you could put an empty `site_base.html` that subclasses whatever your `base.html is. I'm just used to using a `site_base.html` because I base my sites off of `pinax`. https://github.com/pinax/pinax-theme-bootstrap/blob/master/pinax_theme_bootstrap/templates/site_base.html

Here is a rough example:
```
{% extends "base.html" %}

{% load i18n %}

{% block style_base %}
    {% block extra_style %}{% endblock %}
{% endblock %}

{% block header %}
    <div class="container">
        <header class="site-header">
            <h1 class="logo">
                <a href="/"><img src="" alt="" ></a>
            </h1>
            <nav class="navbar-default main-nav" role="navigation">
            </nav>
        </header>
    </div>
{% endblock %}

{% block body %}
    <section class="content">
        {% block content %}{% endblock %}
    </section>
{% endblock %}

{% block extra_script %}
{% endblock %}
```

**Comment by rizumu** [comment]
If you find a better way, feel free to re-open submit a PR.
